version: "3.0"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    working_dir: /tf
    environment:
      - JUPYTER_TOKEN=hi
    volumes:
      - $PWD/work:/tf/work
    ports:
      - 5678:8888
    container_name: internship
